INVENTORY_SLOTS         equ     $ce22
MIRACLE_GLOVE           equ     9

SECTION "miracle_glove", ROMX[$41b0], BANK[$1f]
miracle_glove:
            ld      hl, INVENTORY_SLOTS+1       ; Empty inventory slots...
            ld      [hl+], a                    ; 2, ...
            ld      [hl+], a                    ; 3, ...
            ld      [hl], a                     ; and 4.
            ld      a, MIRACLE_GLOVE            ; Put miracle glove...
            ld      [INVENTORY_SLOTS], a        ; into slot 1.
            nop
